GET http://127.0.0.1:5000

###

GET http://127.0.0.1:5000/isbn/1

###

GET http://127.0.0.1:5000/author/Unknown

###

GET http://127.0.0.1:5000/title/The Epic Of Gilgamesh

###

GET http://127.0.0.1:5000/review/10
###

### Register
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
    "username": "guest",
    "password": "admin"
}
###

POST http://127.0.0.1:5000/customer/login
Content-Type: application/json

{
    "username": "guest",
    "password": "admin"
}
###

PUT http://127.0.0.1:5000/customer/auth/review/1
Content-Type: application/json

{
    "review": "testing"
}

###
DELETE http://127.0.0.1:5000/customer/auth/review/10


###
GET http://127.0.0.1:5000/promise/books

###